name: taraweeh
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.1.0
  async: ^2.0.8
  cloud_firestore: ^0.16.0+1
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  flutter_slidable: ^0.5.7
  gender_picker: ^1.0.4
  get_it: ^3.0.0+1
  http: ^0.12.0
  modal_progress_hud: ^0.1.3
  provider: ^4.3.2+2
  provider_architecture: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
